SELECT
'Quantité'=ISNULL(ROUND(SUM(CASE WHEN ISNULL(FAMILLE,'')='RC' THEN 0 ELSE CASE FA.TYPE WHEN 'FA' THEN  
(ISNULL(QTE_FACT*ISNULL(LF.RAPPORTFA,1),0)) ELSE -(ISNULL(QTE_FACT*ISNULL(LF.RAPPORTFA,1),0)) END END),3), ''),
'Chiffre d''affaires'=ROUND(SUM((CASE FA.TYPE WHEN 'FA' THEN 1 ELSE -1 END)*
(LF.MT_BRUT-LF.MT_REM-LF.MT_ESC)/(CASE FA.TX_DEVISE WHEN 0 THEN 1 ELSE FA.TX_DEVISE END)),3),
'Coût'=(CASE AR.VALORISATION WHEN 1 THEN ISNULL(CS.PRX_ACT,0) WHEN 2 THEN ISNULL(CS.PRX_STD,0) 
WHEN 3 THEN ISNULL(CS.COUT_PUMP,0) WHEN 4 THEN ISNULL(CS.PRX_FAACT,0) ELSE 0 END) *
(ROUND(SUM(CASE WHEN ISNULL(FAMILLE,'')='RC' THEN 0 ELSE CASE FA.TYPE WHEN 'FA' THEN
(ISNULL(QTE_FACT*ISNULL(LF.RAPPORTFA,1),0)) ELSE -(ISNULL(QTE_FACT*ISNULL(LF.RAPPORTFA,1),0)) END END),3)),

'#Date'=CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3),
'#Article'=ISNULL(LF.CDE_PROD, ''),
'#Client'=ISNULL(C.CDE_CLI, '')

FROM AGS.FACTURE FA 
INNER JOIN AGS.LIGFACT LF ON FA.NUM_FACT=LF.NUM_FACT 
INNER JOIN AGS.CLIENTS C ON FA.CDE_CLI=C.CDE_CLI 
INNER JOIN AGS.ARTICLE AR ON LF.CDE_PROD=AR.CDE_PROD 
INNER JOIN AGS.COUTS_STATS CS ON AR.CDE_PROD=CS.CDE_PROD

LEFT OUTER JOIN AGS.VENDEUR V ON ISNULL(FA.VENDEUR,C.VENDEUR)=V.VENDEUR 
LEFT OUTER JOIN AGS.GROUPETIERS GRP ON GRP.CDE_GROUPETIERS = C.GROUPE 
LEFT OUTER JOIN AGS.LIGPROD LP ON AR.LIG_PROD =LP.LIG_PROD 
LEFT OUTER JOIN AGS.PRODUIT PR ON AR.FAM_PROD =PR.CDE_FAM 
LEFT OUTER JOIN AGS.TABLES QUAL ON AR.QUALITE=QUAL.CDE_TABLE AND QUAL.NUM_TABLE=44
LEFT OUTER JOIN AGS.TABLES CAT ON FA.CATEGORIE=CAT.CDE_TABLE AND CAT.NUM_TABLE=132

WHERE (FA.TYPE IN ('AV','FA')) AND (ISNULL(AR.STAT,0)<>1) AND YEAR(FA.DTE_CREAT)>=YEAR(GETDATE())-5 AND ISNULL(C.STAT,0)<7

GROUP BY C.CDE_CLI, C.NOM_CLI, LF.CDE_PROD, FA.DTE_CREAT, AR.VALORISATION, CS.PRX_ACT, CS.PRX_STD, CS.COUT_PUMP, 
CS.PRX_FAACT, C.GROUPE, C.CATEGORIE, GRP.DESIGNATION, AR.UNITE