SELECT 
'Article - famille'=ISNULL(PR.LIB_30, ISNULL(AR.FAM_PROD, '')),
'Article - désignation'=ISNULL(AR.LIB_30, ''),
'Article - catégorie'=ISNULL(CAT.LIB_50, ''),
'Chiffre d''affaires'=ROUND(SUM((CASE FA.TYPE WHEN 'FA' THEN 1 ELSE -1 END)*
(LF.MT_BRUT-LF.MT_REM-LF.MT_ESC)/(CASE FA.TX_DEVISE WHEN 0 THEN 1 ELSE FA.TX_DEVISE END)),3),

'#Article'=ISNULL(LF.CDE_PROD, '')

FROM AGS.FACTURE FA 
INNER JOIN AGS.LIGFACT LF ON FA.NUM_FACT=LF.NUM_FACT
INNER JOIN AGS.CLIENTS C ON FA.CDE_CLI=C.CDE_CLI
INNER JOIN AGS.ARTICLE AR ON LF.CDE_PROD=AR.CDE_PROD
INNER JOIN AGS.COUTS_STATS CS ON AR.CDE_PROD=CS.CDE_PROD /*A enlever ? */

LEFT OUTER JOIN AGS.LIGPROD LP ON AR.LIG_PROD =LP.LIG_PROD
LEFT OUTER JOIN AGS.PRODUIT PR ON AR.FAM_PROD =PR.CDE_FAM
LEFT OUTER JOIN AGS.SEGMENT SEG ON AR.CDE_CATEGORIE=SEG.CDE_CATEGORIE
LEFT OUTER JOIN AGS.CATEGORIETIERS CATT ON C.CATEGORIE=CATT.CDE_CATEGORIE
LEFT OUTER JOIN AGS.TABLES CAT ON FA.CATEGORIE=CAT.CDE_TABLE AND CAT.NUM_TABLE=132

WHERE (FA.TYPE IN ('AV','FA')) AND (ISNULL(AR.STAT,0)<>1) AND YEAR(FA.DTE_CREAT)>=YEAR(GETDATE())-5 AND ISNULL(C.STAT,0)<7

GROUP BY C.GROUPE, C.CDE_CENTRALE, C.SECTEUR_COMMERCIAL, C.ACTIVITE, C.CDE_CLI, C.NOM_CLI,
LP.LIB_30, AR.FAM_PROD, PR.LIB_30, LF.CDE_PROD, AR.LIB_30, C.PAYS_PAIE, AR.LIG_PROD,
C.CATEGORIE, C.MARCHE, AR.CDE_MARQUE, AR.CDE_CATEGORIE, FA.NUM_FACT, AR.CDE_SEGMENT, FA.DTE_CREAT, CAT.LIB_50