SELECT 
'Date'=CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3),
'Année'=DATEPART(YEAR,CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3)),
'Mois'=DATEPART(MONTH,CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3)),
'Trimestre'=DATEPART(QQ,CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3)),

'Fournisseur'=ISNULL(F.NOM_FRS,ISNULL(F.NOM_FRS, ISNULL(F.NOM_FRS, ''))),
'Prix'=SUM((CASE FA.TYPE WHEN 'FA' THEN 1 ELSE -1 END)*(LF.BRUT_FACT
-LF.MREM_FACT-LF.ESC_FACT)/(CASE FA.TX_DEVISE WHEN 0 THEN 1 ELSE FA.TX_DEVISE END)),
'Quantité'=SUM(CASE WHEN ISNULL(FA.FAMILLE,'')='RC' THEN 0 ELSE CASE FA.TYPE WHEN 'FA' THEN
(ISNULL(QTE_FACT,0)) ELSE -(ISNULL(QTE_FACT,0)) END END),

'Article - désignation'=ISNULL(AR.LIB_30, ''),
'Article - famille'=ISNULL(PR.LIB_30, ISNULL(AR.FAM_PROD, ''))

FROM AGEMASRV.CTRLFACT FA

INNER JOIN AGEMASRV.LCTRLFACT LF ON FA.NUM_FACT=LF.NUM_FACT
INNER JOIN AGEMASRV.CTRLFACTHISTO FH ON LF.NUM_FACT=FH.NUM_FACT AND LF.LIG_FACT=FH.LIG_FACT
INNER JOIN AGEMASRV.FOURNIS F ON F.CDE_FRS=FA.CDE_FRS
INNER JOIN AGEMASRV.ARTICLE AR ON LF.CDE_PROD=AR.CDE_PROD
LEFT OUTER JOIN AGEMASRV.CONTRAT AF ON FH.CONTRAT=AF.NUM_AFFAIRE
LEFT OUTER JOIN AGEMASRV.CLIENTS C ON AF.CDE_CLI=C.CDE_CLI
LEFT OUTER JOIN AGEMASRV.TABLES PP ON F.PAYS_PAIE=PP.CDE_TABLE AND PP.NUM_TABLE=35
LEFT OUTER JOIN AGEMASRV.PRODUIT PR ON AR.FAM_PROD =PR.CDE_FAM

WHERE FA.TYPE IN ('AV','FA')
AND ISNULL(F.STAT,0)=0
AND AR.STAT<>1
AND FA.TRANSPORT =0

GROUP BY F.CDE_FRS ,F.NOM_FRS ,LF.CDE_PROD ,AR.LIB_30 ,FA.DTE_CREAT, PR.LIB_30, AR.FAM_PROD, LF.CDE_PROD,
DATEPART(YEAR,CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3)),
DATEPART(MONTH,CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3)), 
DATEPART(QQ,CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3))
