SELECT
'Date'=CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3),
'Mois'=DATEPART(MONTH,CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3)),
'Année'=DATEPART(YEAR,CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3)),
'Trimestre'=DATEPART(QQ,CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3)),

'Pays'=ISNULL(PP.LIB_50, ISNULL(C.PAYS_PAIE, '')),
'Marché'=ISNULL(TYP.DESIGNATION, ISNULL(C.MARCHE, '')),
'Secteur commercial'=ISNULL(SEC.LIB_50, ISNULL(C.SECTEUR_COMMERCIAL, '')),
'Vendeur'=ISNULL(V.NOM,ISNULL(FA.VENDEUR, ISNULL(C.VENDEUR, ''))),
'Ligne de produits'=ISNULL(LP.LIB_30, ISNULL(AR.LIG_PROD, '')),
'Marque'=ISNULL(MAR.DESIGNATION, ISNULL(AR.CDE_MARQUE, '')),
'Catégorie'=ISNULL(CAT.DESIGNATION, ISNULL(AR.CDE_CATEGORIE, '')),
'Segment'=ISNULL(SEG.DESIGNATION, ISNULL(AR.CDE_SEGMENT, '')),
'Activité'=ISNULL(AC.DESIGNATION, ISNULL(C.ACTIVITE, '')),
'Centrale'=ISNULL(CEN.DESIGNATION, ISNULL(C.CDE_CENTRALE, '')),

'Quantité'=ISNULL(ROUND(SUM(CASE WHEN ISNULL(FAMILLE,'')='RC' THEN 0 ELSE CASE FA.TYPE WHEN 'FA' THEN  
(ISNULL(QTE_FACT*ISNULL(LF.RAPPORTFA,1),0)) ELSE -(ISNULL(QTE_FACT*ISNULL(LF.RAPPORTFA,1),0)) END END),3), ''),
'Chiffre d''affaires'=ROUND(SUM((CASE FA.TYPE WHEN 'FA' THEN 1 ELSE -1 END)*
(LF.MT_BRUT-LF.MT_REM-LF.MT_ESC)/(CASE FA.TX_DEVISE WHEN 0 THEN 1 ELSE FA.TX_DEVISE END)),3)

FROM AGEMASRV.FACTURE FA 
INNER JOIN AGEMASRV.LIGFACT LF ON FA.NUM_FACT=LF.NUM_FACT
INNER JOIN AGEMASRV.CLIENTS C ON FA.CDE_CLI=C.CDE_CLI
INNER JOIN AGEMASRV.ARTICLE AR ON LF.CDE_PROD=AR.CDE_PROD
INNER JOIN AGEMASRV.COUTS_STATS CS ON AR.CDE_PROD=CS.CDE_PROD
LEFT OUTER JOIN AGEMASRV.VENDEUR V ON ISNULL(FA.VENDEUR,C.VENDEUR)=V.VENDEUR
LEFT OUTER JOIN AGEMASRV.MARCHE TYP ON C.MARCHE=TYP.CDE_MARCHE
LEFT OUTER JOIN AGEMASRV.CATEGORIETIERS CATT ON C.CATEGORIE=CATT.CDE_CATEGORIE
LEFT OUTER JOIN AGEMASRV.ACTIVITETIERS AC ON C.ACTIVITE=AC.CDE_ACTIVITE AND C.MARCHE=AC.CDE_MARCHE
AND C.ACTIVITE=CATT.CDE_ACTIVITE AND C.MARCHE=CATT.CDE_MARCHE
LEFT OUTER JOIN AGEMASRV.TABLES SEC ON C.SECTEUR_COMMERCIAL=SEC.CDE_TABLE AND SEC.NUM_TABLE=53
LEFT OUTER JOIN AGEMASRV.TABLES PP ON C.PAYS_PAIE=PP.CDE_TABLE AND PP.NUM_TABLE=35
LEFT OUTER JOIN AGEMASRV.MARQUE MAR ON AR.CDE_MARQUE=MAR.CDE_MARQUE
LEFT OUTER JOIN AGEMASRV.CATEGORIE CAT ON AR.CDE_CATEGORIE=CAT.CDE_CATEGORIE AND AR.CDE_MARQUE=CAT.CDE_MARQUE
LEFT OUTER JOIN AGEMASRV.SEGMENT SEG ON AR.CDE_CATEGORIE=SEG.CDE_CATEGORIE
AND AR.CDE_SEGMENT=SEG.CDE_SEGMENT AND AR.CDE_MARQUE=SEG.CDE_MARQUE
LEFT OUTER JOIN AGEMASRV.CENTRALETIERS CEN ON CEN.CDE_CENTRALETIERS = C.CDE_CENTRALE
AND C.SOUS_GROUPE=CEN.CDE_SGROUPETIERS
LEFT OUTER JOIN AGEMASRV.LIGPROD LP ON AR.LIG_PROD =LP.LIG_PROD

WHERE (FA.TYPE IN ('AV','FA')) AND (ISNULL(AR.STAT,0)<>1) AND YEAR(FA.DTE_CREAT)>=YEAR(GETDATE())-3 AND ISNULL(C.STAT,0)<7
GROUP BY FA.VENDEUR, C.VENDEUR, V.NOM, C.GROUPE, C.CDE_CENTRALE, 
CEN.DESIGNATION, C.SECTEUR_COMMERCIAL, SEC.LIB_50, C.ACTIVITE, C.CDE_CLI, C.NOM_CLI, AR.LIG_PROD, 
LP.LIB_30, AR.FAM_PROD, LF.CDE_PROD, AR.LIB_30, AR.ORGANE, C.PAYS_PAIE, PP.LIB_50, AC.DESIGNATION,
C.CATEGORIE, CATT.DESIGNATION, C.MARCHE, TYP.DESIGNATION, AR.CDE_MARQUE, MAR.DESIGNATION, AR.CDE_CATEGORIE, CAT.DESIGNATION, 
AR.CDE_SEGMENT, SEG.DESIGNATION, FA.DTE_CREAT, AR.VALORISATION, CS.PRX_ACT, CS.PRX_STD, CS.COUT_PUMP, CS.PRX_FAACT,
DATEPART(MONTH,CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3)), 
DATEPART(QQ,CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3)),
DATEPART(YEAR,CONVERT(DATETIME,DATEADD(DD,FA.DTE_CREAT,'30/12/1899'),3))